### ISSUE TITLE
How can i access Gdrama Editor? I can't find it anywhere... 

### ISSUE THREAD

**Issue by WithAngeloDev** [moraguma/GDrama#18]
I don't know how to access GDrama editor like shown in the screenshots...

**Comment by moraguma** [comment]
Hey! Here's a quick tutorial. First, right click wherever you want to create your GDrama file and select Create New>TextFile...

![image](https://github.com/moraguma/GDrama/assets/63124011/92d81abe-db06-40a3-9b4e-0252487f4be5)

Then, name your file with the .gdrama extension.

![image](https://github.com/moraguma/GDrama/assets/63124011/387f1db0-eadf-4314-aea6-afcb808e8af0)

If you installed the plugin correctly, the file should be editable with the syntax highlighter!

![image](https://github.com/moraguma/GDrama/assets/63124011/775de596-da0c-4abe-9eb8-8dbf0370262c)

I also updated the README to link to this issue if anyone else is having trouble :)

**Comment by WithAngeloDev** [comment]
> @WithAngeloDev Hey! Here's a quick tutorial. First, right click wherever you want to create your GDrama file and select Create New>TextFile...
> 
> ![image](https://private-user-images.githubusercontent.com/63124011/339836536-92d81abe-db06-40a3-9b4e-0252487f4be5.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTU5MzEsIm5iZiI6MTcxODQ1NTYzMSwicGF0aCI6Ii82MzEyNDAxMS8zMzk4MzY1MzYtOTJkODFhYmUtZGIwNi00MGEzLTliNGUtMDI1MjQ4N2Y0YmU1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEyNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIxZWQ5NDVhMGE0ZmQ5ZGQ5Mjg2Y2U1Yzk2MjFhNmFjOTMzOTFlMGU3M2NkZjY4MjM4NzM4OTA5NDM0NTRhYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._xhQCR2_9S5KEJsQDdGuuKX_aU0oWF8Um07NnvZvzbI)
> 
> Then, name your file with the .gdrama extension.
> 
> ![image](https://private-user-images.githubusercontent.com/63124011/339836626-387f1db0-eadf-4314-aea6-afcb808e8af0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTU5MzEsIm5iZiI6MTcxODQ1NTYzMSwicGF0aCI6Ii82MzEyNDAxMS8zMzk4MzY2MjYtMzg3ZjFkYjAtZWFkZi00MzE0LWFlYTYtYWZjYjgwOGU4YWYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEyNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdhMGIwNWJlMDk5MmI0NTc4ZjdhNDU5Nzc3YTU2OTUyZDgwODA4ZmYwN2UxZTkwYmJhYTZhYTdkNDFjMzhiOTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.y7QYnvcphA9Hh_AP-GDJHmcr0u-n_QbjPiGRKpnM1n4)
> 
> If you installed the plugin correctly, the file should be editable with the syntax highlighter!
> 
> ![image](https://private-user-images.githubusercontent.com/63124011/339836773-775de596-da0c-4abe-9eb8-8dbf0370262c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg0NTU5MzEsIm5iZiI6MTcxODQ1NTYzMSwicGF0aCI6Ii82MzEyNDAxMS8zMzk4MzY3NzMtNzc1ZGU1OTYtZGEwYy00YWJlLTllYjgtOGRiZjAzNzAyNjJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE1VDEyNDcxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExNzAzYmFkOTNjOWFhNjM5N2JkZmNiYjNjYWJlNjEyMTBhNDE4NWIwMDQyMDdmZjg2YjYzODc4NWI2YjJiOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.whAS8O9W8UmsL_xQTkv_fpNamhMG2rjYvbs4uL058WE)
> 
> I also updated the README to link to this issue if anyone else is having trouble :)

Yeah i figured that out after banging my head 12 times into the keyboard XD ,I'm rly sorry if i wasted ur time...
